name: iOS Unit Tests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'Smart Home.xcworkspace' }}
      XC_SCHEME_TESTS: ${{ 'Smart HomeTests' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME_TESTS" -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4'
